import { useMemo, useState } from 'react';
import { useLocation, useParams } from 'wouter';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowUpRight, Plus, Save, Trash2 } from 'lucide-react';
import { getGetCivicRecordsQueryKey, getGetCivicRecordQueryKey, useDeleteCivicRecord, useGetCivicRecord, useGetCivicRecords, useGetAreaSummary, getGetAreaSummaryQueryKey, useUpdateCivicRecord, getGetCurrentProfileQueryKey, useGetCurrentProfile } from '@workspace/api-client-react';
import type { CivicRecordPatch, CivicResource } from '@workspace/api-client-react';
import { Button, Card, EmptyState, ErrorState, LoadingState, PageHeading, StatusPill } from '@/components/ui-kit';
import { ResourceForm } from '@/components/resource-form';

const descriptors: Record<CivicResource,{title:string;subtitle:string;singular:string;icon:string}> = {
  complaints:{title:'Complaints',subtitle:'Review, assign and resolve service requests from the community.',singular:'complaint',icon:'Community reports'},
  infrastructure:{title:'Infrastructure',subtitle:'Monitor public assets, condition and inspection activity.',singular:'asset',icon:'City assets'},
  sanitation:{title:'Sanitation',subtitle:'Coordinate collection schedules and neighborhood cleanliness.',singular:'sanitation record',icon:'Collection operations'},
  maintenance:{title:'Maintenance',subtitle:'Track work orders, teams and planned completion dates.',singular:'work order',icon:'Work orders'},
  areas:{title:'Areas',subtitle:'See neighborhood-level service activity and population context.',singular:'area',icon:'Area directory'},
};
const displayTitle = (record: {title?:string|null;name?:string|null;category?:string|null;asset_type?:string|null}) => record.title || record.name || record.category || record.asset_type || 'Untitled record';
const recordCode = (record: {complaint_number?:string|null;maintenance_number?:string|null;asset_number?:string|null;code?:string|null;id:string}) => record.complaint_number || record.maintenance_number || record.asset_number || record.code || record.id.slice(0,8).toUpperCase();

export function ResourcePage({resource}:{resource:CivicResource}) {
  const [location,navigate]=useLocation();
  const params=useParams<{id?:string}>();
  const id=params.id;
  const profile=useGetCurrentProfile({query:{queryKey:getGetCurrentProfileQueryKey()}});
  const role=profile.data?.role;
  const canCreate=role==='admin'||role==='municipal_officer';
  const canUpdate=canCreate||role==='department_officer';
  const canDelete=role==='admin';
  const [search,setSearch]=useState('');
  const [status,setStatus]=useState('');
  const [showCreate,setShowCreate]=useState(false);
  const [showEdit,setShowEdit]=useState(false);
  const queryParams=useMemo(()=>({search:search||undefined,status:status||undefined,page:1,page_size:50,sort:'created_at',direction:'desc' as const}),[search,status]);
  const statusOptions=resource==='complaints'?['Pending','In Progress','Resolved','Rejected']:resource==='infrastructure'?['Operational','Needs Maintenance','Under Repair','Non Operational']:resource==='sanitation'?['Scheduled','Collected','Delayed','Missed']:resource==='maintenance'?['Planned','In Progress','Completed','Delayed','Cancelled']:[];
  const list=useGetCivicRecords(resource,queryParams);
  const detail=useGetCivicRecord(resource,id||'',{query:{queryKey:getGetCivicRecordQueryKey(resource,id||''),enabled:!!id}});
  const areaSummary=useGetAreaSummary(id||'',{query:{queryKey:getGetAreaSummaryQueryKey(id||''),enabled:resource==='areas'&&!!id}});
  const update=useUpdateCivicRecord();
  const remove=useDeleteCivicRecord();
  const client=useQueryClient();
  const spec=descriptors[resource];
  if(id) {
    if(detail.isLoading)return <LoadingState label="Loading civic record"/>;
    if(detail.isError||!detail.data)return <ErrorState retry={()=>detail.refetch()} message="This record could not be found or is not available to your account."/>;
    const record=detail.data;
    const updateRecord=(data:CivicRecordPatch)=>update.mutate({resource,id,data},{onSuccess:()=>{client.invalidateQueries({queryKey:getGetCivicRecordQueryKey(resource,id)});client.invalidateQueries({queryKey:getGetCivicRecordsQueryKey(resource)});if(resource==='areas')client.invalidateQueries({queryKey:getGetAreaSummaryQueryKey(id)});}});
    const transition: {label:string;data:CivicRecordPatch}|null=resource==='complaints'?record.status==='Resolved'?{label:'Reopen complaint',data:{status:'In Progress',resolved_at:undefined}}:{label:'Mark resolved',data:{status:'Resolved',resolved_at:new Date().toISOString()}}:resource==='maintenance'?record.status==='Completed'?{label:'Reopen work order',data:{status:'In Progress',progress:75,actual_completion:undefined}}:{label:'Complete work order',data:{status:'Completed',progress:100,actual_completion:new Date().toISOString().slice(0,10)}}:resource==='infrastructure'?{label:'Record inspection',data:{last_inspection:new Date().toISOString().slice(0,10)}}:resource==='sanitation'?{label:record.collection_status==='Collected'?'Schedule collection':'Mark collected',data:{collection_status:record.collection_status==='Collected'?'Scheduled':'Collected',last_collection:record.collection_status==='Collected'?undefined:new Date().toISOString()}}:null;
    const area=areaSummary.data;
    return <div><button onClick={()=>navigate(`/${resource}`)} className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/>Back to {spec.title.toLowerCase()}</button><PageHeading eyebrow={`${spec.icon} · ${recordCode(record)}`} title={displayTitle(record)} description={record.description||record.location||'Municipal record details and current assignment.'} action={<StatusPill value={record.status||record.condition||record.collection_status}/>}/>
      <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card className="p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">Record details</h3><p className="mt-1 text-xs text-muted-foreground">Review the record and current assignment.</p></div><div className="flex flex-wrap gap-2">{canUpdate&&<Button variant="outline" onClick={()=>setShowEdit(true)}>Edit record</Button>}{canUpdate&&transition&&<Button disabled={update.isPending} onClick={()=>updateRecord(transition.data)}><Save className="h-4 w-4"/>{transition.label}</Button>}</div></div>
      <div className="grid gap-x-8 gap-y-5 sm:grid-cols-2">{[['Category',record.category||record.asset_type],['Priority',record.priority],['Location',record.location],['Area',record.area_name],['Department',record.assigned_department],['Officer / team',record.assigned_officer||record.assigned_team],['Reported',record.reported_at||record.created_at],['Last updated',record.updated_at],['Condition',record.condition],['Progress',record.progress==null?null:`${record.progress}%`]].map(([label,value])=><div key={label as string}><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value||'Not recorded'}</p></div>)}</div>
      {resource!=='areas'&&<label className="mt-7 block text-xs font-bold uppercase tracking-wider text-muted-foreground">Operational notes<textarea key={record.id} defaultValue={record.notes||''} onBlur={event=>{if(canUpdate&&event.target.value!==record.notes)updateRecord({notes:event.target.value});}} disabled={!canUpdate} rows={4} placeholder="Add a field note for the next team…" className="mt-2 w-full rounded-lg border border-input bg-background p-3 text-sm font-normal normal-case tracking-normal outline-none focus:ring-2 focus:ring-ring disabled:opacity-60"/></label>}
      {update.isError&&<p className="mt-2 text-sm text-destructive">Could not save the update. Please retry.</p>}</Card>
      <div className="space-y-5">{resource==='areas'&&<Card className="p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">Area service summary</h3><ArrowUpRight className="h-4 w-4 text-primary"/></div>{areaSummary.isLoading?<div className="h-24 animate-pulse rounded bg-muted"/>:areaSummary.isError?<p className="text-sm text-muted-foreground">Area summary is unavailable.</p>:area&&<div className="grid grid-cols-2 gap-3">{[['Total complaints',area.total_complaints],['Pending',area.pending_complaints],['Infrastructure',area.infrastructure_issues],['Sanitation',area.sanitation_issues],['Maintenance',area.active_maintenance]].map(([label,value])=><div key={label as string} className="rounded-lg bg-muted/60 p-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 font-mono text-xl font-bold">{value}</p></div>)}</div>}</Card>}<Card className="p-5"><h3 className="font-bold">Record reference</h3><p className="mt-2 font-mono text-sm text-muted-foreground">{recordCode(record)}</p><p className="mt-4 text-xs leading-5 text-muted-foreground">Updates are recorded in the city’s shared operations system for authorized staff.</p>{canDelete&&<Button variant="danger" className="mt-5" onClick={()=>{if(window.confirm(`Delete this ${spec.singular}? This action cannot be undone.`))remove.mutate({resource,id},{onSuccess:()=>{client.invalidateQueries({queryKey:getGetCivicRecordsQueryKey(resource)});navigate(`/${resource}`);}});}} disabled={remove.isPending}><Trash2 className="h-4 w-4"/>Delete record</Button>}{remove.isError&&<p className="mt-2 text-xs text-destructive">Unable to delete this record.</p>}</Card></div></div>{showEdit&&<ResourceForm resource={resource} initial={record} close={()=>setShowEdit(false)}/>}</div>;
  }
  if(list.isLoading)return <LoadingState/>;
  if(list.isError||!list.data)return <ErrorState retry={()=>list.refetch()}/>;
  return <div><PageHeading eyebrow={spec.icon} title={spec.title} description={spec.subtitle} action={canCreate?<Button onClick={()=>setShowCreate(true)}><Plus className="h-4 w-4"/>Add {spec.singular}</Button>:undefined}/>
    <Card className="mb-5 flex flex-col gap-3 p-4 sm:flex-row"><input aria-label={`Search ${spec.title}`} data-testid={`input-search-${resource}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${spec.title.toLowerCase()}…`} className="h-10 flex-1 rounded-lg border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"/>{statusOptions.length>0&&<select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-lg border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="">All statuses</option>{statusOptions.map(value=><option key={value} value={value}>{value}</option>)}</select>}<span className="self-center px-2 text-xs text-muted-foreground">{list.data.total} records</span></Card>
    {list.data.items.length===0?<EmptyState title={`No ${spec.title.toLowerCase()} found`} detail={search||status?'Try adjusting your filters.':'Create the first record to begin tracking this service area.'}/>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-muted/65 text-[10px] uppercase tracking-wider text-muted-foreground"><tr>{['Record','Location / area','Category','Priority','Status','Updated',''].map(label=><th key={label} className="px-5 py-3.5 font-bold">{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{list.data.items.map((record,index)=><tr key={record.id} className="transition hover:bg-muted/45" data-testid={`row-${resource}-${record.id}`}><td className="px-5 py-4"><button onClick={()=>navigate(`/${resource}/${record.id}`)} className="text-left"><p className="text-sm font-semibold hover:text-primary">{displayTitle(record)}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{recordCode(record)}</p></button></td><td className="px-5 py-4"><p className="text-xs font-medium">{record.area_name||record.location||'Not specified'}</p><p className="mt-1 text-[10px] text-muted-foreground">{record.location&&record.area_name?record.location:''}</p></td><td className="px-5 py-4 text-xs">{record.category||record.asset_type||'—'}</td><td className="px-5 py-4"><StatusPill value={record.priority}/></td><td className="px-5 py-4"><StatusPill value={record.status||record.condition||record.collection_status}/></td><td className="px-5 py-4 text-xs text-muted-foreground">{record.updated_at?new Date(record.updated_at).toLocaleDateString():record.reported_at?new Date(record.reported_at).toLocaleDateString():'—'}</td><td className="px-5 py-4"><button aria-label={`Open record ${recordCode(record)}`} onClick={()=>navigate(`/${resource}/${record.id}`)} className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-primary"><ArrowUpRight className="h-4 w-4"/></button></td></tr>)}</tbody></table></div></Card>}
    {showCreate&&<ResourceForm resource={resource} close={()=>setShowCreate(false)}/>}
  </div>;
}
