import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Bell, Check, CheckCheck, Download, FileBarChart2, Moon, Sun } from 'lucide-react';
import { getGetCivicReportQueryKey, getGetNotificationsQueryKey, getGetCurrentProfileQueryKey, getApiHealthCheckQueryKey, useGetCivicReport, useGetNotifications, useGetCurrentProfile, useApiHealthCheck, useMarkNotificationRead, getGetCivicRecordsQueryKey, useGetCivicRecords } from '@workspace/api-client-react';
import type { CivicResource, GetCivicReportParams } from '@workspace/api-client-react';
import { Button, Card, EmptyState, ErrorState, LoadingState, PageHeading, StatusPill } from '@/components/ui-kit';
import { useTheme } from '@/components/theme-provider';
import { useAuth } from '@/components/auth-provider';
import { supabase } from '@/lib/supabase';

export function ReportsPage() {
  const [resource,setResource]=useState<CivicResource>('complaints');
  const [area,setArea]=useState('');
  const [status,setStatus]=useState('');
  const [start,setStart]=useState('');
  const [end,setEnd]=useState('');
  const [requested,setRequested]=useState(false);
  const areas=useGetCivicRecords('areas',{page:1,page_size:100,sort:'name',direction:'asc'});
  const params:GetCivicReportParams={resource,area_id:area||undefined,status:status||undefined,start_date:start||undefined,end_date:end||undefined};
  const report=useGetCivicReport(params,{query:{queryKey:getGetCivicReportQueryKey(params),enabled:requested}});
  const exportCsv=()=>{if(!report.data)return;const columns=['id','title','name','category','location','area_name','priority','status','assigned_department','created_at'];const escape=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;const contents=[columns.join(','),...report.data.items.map(item=>columns.map(key=>escape((item as unknown as Record<string,unknown>)[key])).join(','))].join('\n');const file=new Blob([contents],{type:'text/csv;charset=utf-8;'});const link=document.createElement('a');link.href=URL.createObjectURL(file);link.download=`civic-${resource}-report.csv`;link.click();URL.revokeObjectURL(link.href);};
  return <div><PageHeading eyebrow="Service intelligence" title="Reports" description="Build a filtered view of the records teams use to plan and deliver city services." action={report.data?<Button variant="outline" onClick={exportCsv}><Download className="h-4 w-4"/>Export CSV</Button>:undefined}/>
    <Card className="mb-6 p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><label className="text-xs font-semibold">Resource<select value={resource} onChange={e=>setResource(e.target.value as CivicResource)} className="mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm">{['complaints','infrastructure','sanitation','maintenance','areas'].map(item=><option key={item} value={item}>{item[0].toUpperCase()+item.slice(1)}</option>)}</select></label><label className="text-xs font-semibold">Area<select value={area} onChange={e=>setArea(e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="">All areas</option>{areas.data?.items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-semibold">Status<input value={status} onChange={e=>setStatus(e.target.value)} placeholder="Any status" className="mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"/></label><label className="text-xs font-semibold">From<input type="date" value={start} onChange={e=>setStart(e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"/></label><label className="text-xs font-semibold">To<input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"/></label></div><div className="mt-4 flex justify-end"><Button onClick={()=>setRequested(true)}><FileBarChart2 className="h-4 w-4"/>Generate report</Button></div></Card>
    {!requested?<div className="rounded-xl border border-dashed border-border bg-card/50 py-16 text-center"><FileBarChart2 className="mx-auto h-8 w-8 text-primary/70"/><h3 className="mt-3 font-semibold">Set your reporting scope</h3><p className="mt-1 text-sm text-muted-foreground">Choose filters, then generate a live report from municipal records.</p></div>:report.isLoading?<LoadingState label="Generating report"/>:report.isError?<ErrorState retry={()=>report.refetch()} message="The report could not be generated."/>:report.data?.items.length===0?<EmptyState title="No records match these filters" detail="Change the reporting scope and generate the report again."/>:report.data&&<Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h3 className="font-bold">Filtered records</h3><p className="mt-1 text-xs text-muted-foreground">{report.data.total} results · {report.data.resource}</p></div><Button variant="outline" onClick={exportCsv}><Download className="h-4 w-4"/>Export CSV</Button></div><div className="divide-y divide-border">{report.data.items.map(record=><div key={record.id} className="flex flex-wrap items-center gap-x-5 gap-y-2 px-5 py-4"><div className="min-w-[220px] flex-1"><p className="text-sm font-semibold">{record.title||record.name||record.category||'Civic record'}</p><p className="mt-1 text-xs text-muted-foreground">{record.area_name||record.location||'Location not specified'}</p></div><StatusPill value={record.priority}/><StatusPill value={record.status||record.condition}/><span className="text-xs text-muted-foreground">{record.created_at?new Date(record.created_at).toLocaleDateString():'—'}</span></div>)}</div></Card>}
  </div>;
}

export function NotificationsPage() {
  const query=useGetNotifications({query:{queryKey:getGetNotificationsQueryKey()}});
  const mark=useMarkNotificationRead();
  const client=useQueryClient();
  const unread=query.data?.filter(item=>!item.is_read)||[];
  const markRead=(id:string)=>mark.mutate({id},{onSuccess:()=>client.invalidateQueries({queryKey:getGetNotificationsQueryKey()})});
  return <div><PageHeading eyebrow="Your inbox" title="Notifications" description="Service updates and operational notices for your signed-in profile." action={unread.length>0?<Button variant="outline" onClick={()=>unread.forEach(item=>markRead(item.id))}><CheckCheck className="h-4 w-4"/>Mark all read</Button>:undefined}/>{query.isLoading?<LoadingState/>:query.isError?<ErrorState retry={()=>query.refetch()}/>:!query.data?.length?<EmptyState title="You are all caught up" detail="New service notifications will appear here."/>:<Card className="overflow-hidden"><div className="divide-y divide-border">{query.data.map(item=><article key={item.id} className={`flex gap-4 p-5 transition ${item.is_read?'opacity-75':'bg-primary/[.035]'}`} data-testid={`notification-${item.id}`}><div className={`mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-full ${item.is_read?'bg-muted text-muted-foreground':'bg-secondary text-secondary-foreground'}`}><Bell className="h-4 w-4"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold">{item.title}</h3><StatusPill value={item.type}/>{!item.is_read&&<span className="h-2 w-2 rounded-full bg-primary"/>}</div><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.message}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(item.created_at).toLocaleString()}</p></div>{!item.is_read&&<button aria-label={`Mark ${item.title} read`} disabled={mark.isPending} onClick={()=>markRead(item.id)} className="self-start rounded-lg border border-border p-2 text-muted-foreground hover:bg-muted hover:text-primary"><Check className="h-4 w-4"/></button>}</article>)}</div></Card>}</div>;
}

export function SettingsPage() {
  const profile=useGetCurrentProfile({query:{queryKey:getGetCurrentProfileQueryKey()}});
  const health=useApiHealthCheck({query:{queryKey:getApiHealthCheckQueryKey()}});
  const {theme,toggle}=useTheme();
  const {signOut}=useAuth();
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState('');
  const requestReset=async()=>{setBusy(true);setMessage('');const email=profile.data?.email;if(!email||!supabase){setMessage('Password reset is not available for this profile.');setBusy(false);return;}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});setMessage(error?error.message:`Password reset instructions sent to ${email}.`);setBusy(false);};
  return <div><PageHeading eyebrow="Workspace preferences" title="Settings" description="Manage your profile, session and display preferences."/>
    {profile.isLoading?<LoadingState/>:profile.isError?<ErrorState retry={()=>profile.refetch()}/>:<div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-5"><Card className="p-6"><h3 className="font-bold">Staff profile</h3><p className="mt-1 text-sm text-muted-foreground">Identity and permissions associated with this secure session.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['Full name',profile.data?.full_name],['Email',profile.data?.email],['Role',profile.data?.role],['Department',profile.data?.department]].map(([label,value])=><div key={label as string} className="rounded-lg bg-muted/60 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1.5 text-sm font-semibold">{value||'Not provided'}</p></div>)}</div></Card>
      <Card className="p-6"><div className="flex items-center justify-between"><div><h3 className="font-bold">Appearance</h3><p className="mt-1 text-sm text-muted-foreground">Your preference is saved on this device.</p></div><Button variant="outline" onClick={toggle}>{theme==='light'?<Moon className="h-4 w-4"/>:<Sun className="h-4 w-4"/>}Switch to {theme==='light'?'dark':'light'} mode</Button></div></Card>
      <Card className="p-6"><h3 className="font-bold">Account security</h3><p className="mt-1 text-sm text-muted-foreground">Send a secure password reset link to your account email.</p><div className="mt-4 flex flex-wrap items-center gap-3"><Button variant="outline" disabled={busy} onClick={requestReset}>Send password reset link</Button>{message&&<p role="status" className="text-xs text-muted-foreground">{message}</p>}</div></Card></div>
       <div className="space-y-5"><Card className="p-6"><h3 className="font-bold">Service connection</h3><p className="mt-1 text-sm text-muted-foreground">Status of the city data services for your workspace.</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-sm">Supabase database</span><span className="inline-flex items-center gap-2 text-xs font-semibold"><span className={`h-2 w-2 rounded-full ${health.data?.database==='connected'?'bg-emerald-500':'bg-amber-500'}`}/>{health.data?.database|| (health.isLoading?'Checking':'Unavailable')}</span></div>{health.isError&&<p className="mt-3 text-xs text-destructive">Database service could not be reached. Check Supabase setup.</p>}</Card><Card className="border-destructive/20 p-6"><h3 className="font-bold">Sign out</h3><p className="mt-1 text-sm text-muted-foreground">End your current authorized session on this device.</p><Button variant="outline" className="mt-4" onClick={()=>signOut()}>Sign out of CivicDesk</Button></Card></div></div>}
  </div>;
}
